const globalTypes = {
  CHANGE_THEME: 'CHANGE_THEME',
  OTHER_ACTION: 'OTHER_ACTION',
  START_PUT_SIGN_IN_APP: 'START_PUT_SIGN_IN_APP',
  PUT_SIGN_IN_APP_SUCCESS: 'PUT_SIGN_IN_APP_SUCCESS',
  NOT_ACCESS_PAGE: 'NOT_ACCESS_PAGE',
  SET_EMTPY_DATA_423: 'SET_EMTPY_DATA_423',  
}

export default globalTypes;